### PR TITLE
Update fn_CamInit.sqf

### PR DESCRIPTION
**Pull request by Aptann**
_newUnit is undefined, throws script error. Moving it outside the if scope fixes this.

### CODE REVIEW

**Comment by Wolfenswan** [comment]
Just to confirm: In which line is the script error thrown? 63? Are you using TFAR?

**Comment by Aptann** [comment]
Without my change, line 58
```
[_newUnit, true] call TFAR_fnc_forceSpectator;
```

**Comment by Wolfenswan** [comment]
Yeah, turns out it should be

```
[player, true] call TFAR_fnc_forceSpectator;
```

Cheers for finding this one.

**Comment by Aptann** [comment]
Ah yeah, using player makes more sense than my suggested fix

**Pull request closed without merging**
